### ISSUE TITLE
Team travel booked

### ISSUE THREAD

**Issue by suprenant** [18F/epa-emissions#1]
Confirm travel:
 - [x] Lalitha
 - [x] Nikki
 - [x] Kathryn
 - [x] Andrew

Auths approved and ticketed:
- [ ] Confirmed for group

**Comment by suprenant** [comment]
I've submitted my travel – I'm scheduled to arrive on Monday afternoon and then will depart BHM at 3PM on Wednesday.

**Comment by lalitha-jonnalagadda** [comment]
Submitted my travel - Scheduled to arrive Monday evening and departing Wednesday evening.

**Comment by suprenant** [comment]
From our meeting here, I think we only need to sort out Lalitha's lodging, and then we'll be good to go.

**Comment by lalitha-jonnalagadda** [comment]
Finally have my lodging situation handled as well. Good to close this card!

**Comment by suprenant** [comment]
Sounds like we're good to go. Moving this to Done.
