### ISSUE TITLE
Ship report

### ISSUE THREAD

**Issue by suprenant** [18F/epa-emissions#10]
What we're after:
 - So we are regularly updating our partner and interested parties with our plans, progress, risks, and mitigations, we want to send them a regular update.

Notes:
 - Some notes from when we discussed this are here:
https://docs.google.com/document/d/1Z5aYeWkgnhmuC1qFiMKt1BRjCHAIBW_qDJvnp1ZqEVQ/edit#heading=h.s1efy5dyubrm
 - Include conference attendees

Acceptance criteria:
 - [ ] We can confirm we have sent a report to the partner

**Comment by nikzei** [comment]
Drafted and ready for review. It's [here](https://docs.google.com/document/d/1s4B-H_oT8ZCl8I2RxaPksVfWb0EJMi9mOxU3kUftopA/edit#).

**Comment by lalitha-jonnalagadda** [comment]
Looks great. Good to ship!
