### ISSUE TITLE
Research plan, interview script

### ISSUE THREAD

**Issue by suprenant** [18F/epa-emissions#2]
Scratchpad: https://docs.google.com/document/d/17bFxXLQ6YloiroMpHa9bactguFT9ebxIiO84MhPpJog/edit

**Comment by suprenant** [comment]
From our conversation today, I expect to pick this up between today and tomorrow.

**Comment by suprenant** [comment]
I have a scratchpad questions doc and place for a preliminary research plan that I'm now working on linked above.

**Comment by nikzei** [comment]
Looks like we have a script drafted at the bottom of this research scratchpad? I think we're ready to close this. Also, I suggest pulling out that script from the scratch pad content and making a separate doc.
