### ISSUE TITLE
Opportunities/first impressions and risks outlined

### ISSUE THREAD

**Issue by suprenant** [18F/epa-emissions#5]
https://app.mural.co/t/gsa6/m/gsa6/1556823576770/d68e01289ee2fdf968e4b68e9abacac763e1a0a2

 - [x] Lalitha
 - [x] Nikki
 - [x] Andrew

**Comment by suprenant** [comment]
I've finished my pass – I ran through the 5/1 and also BD notes and added things that caught my attention to our Mural (BD items marked as "(BD)").

**Comment by suprenant** [comment]
@nikzei are you still planning on doing work on the Mural with our initial findings? Or done for now?

**Comment by nikzei** [comment]
I'm done for now and fine closing this. Fwiw, my additions:
- a few stickies to all of your sections;
- a section to shape a narrower scope for the Birmingham trip; and
- a section to identify post-Birmingham work
