### ISSUE TITLE
Birmingham interviews scheduled

### ISSUE THREAD

**Issue by suprenant** [18F/epa-emissions#7]
[Contact list](https://docs.google.com/spreadsheets/d/1FihywOeeNgyzM2ZeznlzXCt6IjBVmx_au9sEr8t7jTs/edit#gid=0)

**Comment by lalitha-jonnalagadda** [comment]
@MKathrynC - I added two columns to the contact list for a scheduled interview slot as well as interviewer/note taker columns. Please add to the list when you have a confirmed appointment.
